# Generated by Django 4.2.7 on 2023-12-01 20:13

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("students", "0002_alter_academicyearstudentfee_academic_year_and_more")]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.PositiveBigIntegerField(default=students.models.get_next_admission_number, unique=True),
        )
    ]
