# Generated by Django 4.2.7 on 2023-12-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("students", "0003_alter_student_admission_number")]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(
                help_text="Enter the division name (e.g., A, B)",
                max_length=50,
                verbose_name="Division",
            ),
        )
    ]
