# Generated by Django 4.2.7 on 2023-12-05 20:45

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("students", "0004_alter_division_name")]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="employees/photos/"),
        ),
        migrations.AddField(
            model_name="student",
            name="ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5",
                editable=False,
                max_length=20,
                verbose_name="Image PPOI",
            ),
        ),
    ]
