# Generated by Django 4.2.7 on 2023-12-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("students", "0005_student_photo_student_ppoi")]

    operations = [
        migrations.AlterField(
            model_name="academicyearstudentfee",
            name="donation_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Admission Fee"),
        )
    ]
