# Generated by Django 4.2.7 on 2023-12-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("students", "0006_alter_academicyearstudentfee_donation_fee")]

    operations = [
        migrations.AddField(
            model_name="academicyearstudentfee",
            name="pta_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        )
    ]
