# Generated by Django 4.2.7 on 2024-01-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("students", "0007_academicyearstudentfee_pta_fee")]

    operations = [
        migrations.AlterField(
            model_name="academicyearstudentfee",
            name="academic_year",
            field=models.CharField(
                choices=[
                    ("2023-2024", "2023-2024"),
                    ("2024-2025", "2024-2025"),
                    ("2025-2026", "2025-2026"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="studentfeestatement",
            name="academic_year",
            field=models.CharField(
                choices=[
                    ("2023-2024", "2023-2024"),
                    ("2024-2025", "2024-2025"),
                    ("2025-2026", "2025-2026"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="studentfeestatement",
            name="voucher_number",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="Receipt Number"),
        ),
    ]
