# Generated by Django 5.0.1 on 2024-07-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_alter_academicyearstudentfee_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
