# Generated by Django 5.2.5 on 2025-08-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyearstudentfee',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], max_length=128),
        ),
        migrations.AlterField(
            model_name='studentfeestatement',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], max_length=128),
        ),
    ]
