# Generated by Django 5.2.5 on 2025-08-21 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_academicyearstudentfee_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.standard'),
        ),
    ]
