# Generated by Django 4.2.7 on 2023-11-25 12:02

import django.db.models.deletion
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("employee_id", models.CharField(max_length=128, unique=True)),
                ("first_name", models.CharField(max_length=300)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("married", "Married"),
                            ("single", "Single"),
                            ("in_a_relationship", "In a Relationship"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=128, null=True),
                ),
                ("mobile", models.CharField(blank=True, max_length=128, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=128, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("religion", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="employees/photos/"),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                (
                    "official_email",
                    models.EmailField(blank=True, max_length=128, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "father_mobile",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "guardian_mobile",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "relationship_with_employee",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("date_of_confirmation", models.DateField(blank=True, null=True)),
                (
                    "type_of_residence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SELF_OWNED", "Self Owned"),
                            ("FAMILY_OWNED", "Family Owned"),
                            ("SELF_RENTED", "Self Rented"),
                            ("FAMILY_RENTED", "Family Rented"),
                            ("COMPANY_RENTED", "Company Rented"),
                            ("COMPANY_OWNED", "Company Owned"),
                            ("SHARED", "Shared"),
                            ("OTHER", "Other"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "residence_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("residential_address", models.TextField(blank=True, null=True)),
                (
                    "residence_contact",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "residential_postal_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("permanent_address", models.TextField(blank=True, null=True)),
                (
                    "permanent_postal_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Bank Account Number",
                    ),
                ),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Bank IFSC Code",
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="PAN Card Number",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("PROBATION", "Probation"),
                            ("CONTRACT", "Contract"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a-positive", "A +Ve"),
                            ("b-positive", "B +Ve"),
                            ("ab-positive", "AB +Ve"),
                            ("o-positive", "O +Ve"),
                            ("a-negative", "A -Ve"),
                            ("b-negative", "B -Ve"),
                            ("ab-negative", "AB -Ve"),
                            ("o-negative", "O -Ve"),
                        ],
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.designation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={
                            "is_active": True,
                            "is_superuser": False,
                            "usertype__in": (
                                "management",
                                "teacher",
                                "worker",
                                "accountant",
                            ),
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePayroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Salary"),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                ("year", models.IntegerField(choices=[(2023, 2023), (2024, 2024)])),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Payroll",
                "verbose_name_plural": "Employee Payrolls",
            },
        ),
        migrations.CreateModel(
            name="EmployeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "voucher_number",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Payment Voucher",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_payment_account",
                        to="accounting.account",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employee",
                    ),
                ),
            ],
            options={"ordering": ("-date",)},
        ),
        migrations.AddField(
            model_name="department",
            name="department_lead",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="department_list",
                to="employees.employee",
            ),
        ),
    ]
