# Generated by Django 4.2.7 on 2024-01-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("employees", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="employeepayroll",
            name="year",
            field=models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025)]),
        )
    ]
