# Generated by Django 5.2.5 on 2025-08-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeepayroll_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayroll',
            name='year',
            field=models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)]),
        ),
    ]
