# Generated by Django 4.2.7 on 2023-11-25 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalFeeStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        choices=[
                            ("", "Select Academic Year"),
                            ("2023-2024", "2023-2024"),
                            ("2024-2025", "2024-2025"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "fee",
                    models.CharField(
                        choices=[
                            ("uniform_fee", "Uniform Fee"),
                            ("book_fee", "Book Fee"),
                            ("worksheet_fee", "Worksheet Fee"),
                            ("other", "Other Fee"),
                        ],
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_additional_fees",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Fee student",
                "verbose_name_plural": "Additional Fee studentes",
                "ordering": ("academic_year", "-due_date"),
            },
        )
    ]
