# Generated by Django 4.2.7 on 2023-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fees", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="additionalfeestudent",
            name="academic_year",
            field=models.CharField(
                choices=[("2023-2024", "2023-2024"), ("2024-2025", "2024-2025")],
                max_length=128,
            ),
        )
    ]
