# Generated by Django 4.2.7 on 2024-01-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fees", "0002_alter_additionalfeestudent_academic_year")]

    operations = [
        migrations.AlterField(
            model_name="additionalfeestudent",
            name="academic_year",
            field=models.CharField(
                choices=[
                    ("2023-2024", "2023-2024"),
                    ("2024-2025", "2024-2025"),
                    ("2025-2026", "2025-2026"),
                ],
                max_length=128,
            ),
        )
    ]
