# Generated by Django 4.2.7 on 2024-01-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fees", "0003_alter_additionalfeestudent_academic_year")]

    operations = [
        migrations.AlterField(
            model_name="additionalfeestudent",
            name="fee",
            field=models.CharField(
                choices=[
                    ("uniform_fee", "Uniform Fee"),
                    ("book_fee", "Book Fee"),
                    ("worksheet_fee", "Worksheet Fee"),
                    ("pta_fee", "Pta Fee"),
                    ("other", "Other Fee"),
                ],
                max_length=255,
            ),
        )
    ]
