# Generated by Django 5.0.1 on 2024-03-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0004_alter_additionalfeestudent_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalfeestudent",
            name="fee_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
