# Generated by Django 5.2.5 on 2025-08-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_additionalfeestudent_fee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeestudent',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], max_length=128),
        ),
    ]
