# Generated by Django 5.2.5 on 2025-08-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('management', 'Management'), ('student', 'Student'), ('teacher', 'Teacher'), ('accountant', 'Accountant')], default='student', max_length=20),
        ),
    ]
