# Generated by Django 4.2.7 on 2023-11-27 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_alter_academicyearstudentfee_academic_year_and_more"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_marked", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["exam", "marks_obtained"]},
        ),
        migrations.RemoveField(model_name="exam", name="division"),
        migrations.RemoveField(model_name="exam", name="time"),
        migrations.DeleteModel(name="ExamResult"),
        migrations.AddField(
            model_name="studentexam",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="studentexam",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="students.student"),
        ),
        migrations.AlterUniqueTogether(name="studentexam", unique_together={("exam", "student", "is_active")}),
    ]
