# Generated by Django 5.2.5 on 2025-08-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentexam_remove_exam_division_remove_exam_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date']},
        ),
    ]
