# Generated by Django 4.2.7 on 2023-11-27 05:31

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("employees", "0001_initial"), ("courses", "0001_initial")]

    operations = [
        migrations.AlterField(model_name="course", name="description", field=tinymce.models.HTMLField()),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"user__usertype": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.employee",
            ),
        ),
    ]
