# Generated by Django 4.2.7 on 2023-12-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
        ("courses", "0002_alter_course_description_alter_course_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employees.employee"),
        )
    ]
