# Generated by Django 4.2.7 on 2023-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tasks", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="studenttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("in_review", "In Review"),
                    ("completed", "Completed"),
                    ("rework", "Rework"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, help_text="Enter a description for the task", null=True),
        ),
        migrations.AlterUniqueTogether(name="task", unique_together={("title", "due_date")}),
    ]
