# Generated by Django 4.2.7 on 2023-12-05 12:59

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounting", "0002_initial")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="voucher_number",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=accounting.models.get_next_voucher_number,
                null=True,
                unique=True,
                verbose_name="Payment Voucher",
            ),
        )
    ]
